name: Auto Pulling and Pushing Projects

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  Executive:
    runs-on: ubuntu-latest
    steps:
      - name: pulling code from repo
        uses: actions/checkout@v6
      - name: install python version 3.14
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - name: install pip and upgrade pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: run tests with pytest
        run: |
          pip install pytest
          pytest